countries = [ 
{"name": "Italy", "capital": "Rome", "continent": "Europe"},
{"name": "France", "capital": "Paris", "continent": "Europe"},
{"name": "Germany", "capital": "Berlin", "continent": "Europe"},
{"name": "Spain", "capital": "Madrid", "continent": "Europe"},
{"name": "United Kingdom", "capital": "London", "continent": "Europe"},
{"name": "United States", "capital": "Washington D.C.", "continent": "North America"},
{"name": "Canada", "capital": "Ottawa", "continent": "North America"},
{"name": "Mexico", "capital": "Mexico City", "continent": "North America"},
{"name": "Brazil", "capital": "Brasília", "continent": "South America"},
{"name": "Argentina", "capital": "Buenos Aires", "continent": "South America"},
{"name": "Chile", "capital": "Santiago", "continent": "South America"},
{"name": "Peru", "capital": "Lima", "continent": "South America"},
{"name": "Colombia", "capital": "Bogotá", "continent": "South America"},
{"name": "Venezuela", "capital": "Caracas", "continent": "South America"},
{"name": "China", "capital": "Beijing", "continent": "Asia"},
{"name": "Japan", "capital": "Tokyo", "continent": "Asia"},
{"name": "South Korea", "capital": "Seoul", "continent": "Asia"},
{"name": "India", "capital": "New Delhi", "continent": "Asia"},
{"name": "Pakistan", "capital": "Islamabad", "continent": "Asia"},
{"name": "Indonesia", "capital": "Jakarta", "continent": "Asia"},
{"name": "Australia", "capital": "Canberra", "continent": "Oceania"},
{"name": "New Zealand", "capital": "Wellington", "continent": "Oceania"},
{"name": "Egypt", "capital": "Cairo", "continent": "Africa"},
{"name": "Nigeria", "capital": "Abuja", "continent": "Africa"},
{"name": "South Africa", "capital": "Pretoria", "continent": "Africa"},
{"name": "Kenya", "capital": "Nairobi", "continent": "Africa"},
{"name": "Morocco", "capital": "Rabat", "continent": "Africa"},
{"name": "Saudi Arabia", "capital": "Riyadh", "continent": "Asia"},
{"name": "Turkey", "capital": "Ankara", "continent": "Asia"},
{"name": "Russia", "capital": "Moscow", "continent": "Europe/Asia"},
{"name": "Ukraine", "capital": "Kyiv", "continent": "Europe"},
{"name": "Poland", "capital": "Warsaw", "continent": "Europe"},
{"name": "Sweden", "capital": "Stockholm", "continent": "Europe"},
{"name": "Norway", "capital": "Oslo", "continent": "Europe"},
{"name": "Finland", "capital": "Helsinki", "continent": "Europe"},
{"name": "Denmark", "capital": "Copenhagen", "continent": "Europe"},
{"name": "Netherlands", "capital": "Amsterdam", "continent": "Europe"},
{"name": "Belgium", "capital": "Brussels", "continent": "Europe"},
{"name": "Switzerland", "capital": "Bern", "continent": "Europe"},
{"name": "Austria", "capital": "Vienna", "continent": "Europe"},
{"name": "Greece", "capital": "Athens", "continent": "Europe"},
{"name": "Portugal", "capital": "Lisbon", "continent": "Europe"},
{"name": "Ireland", "capital": "Dublin", "continent": "Europe"},
{"name": "Iceland", "capital": "Reykjavik", "continent": "Europe"},
{"name": "Thailand", "capital": "Bangkok", "continent": "Asia"},
{"name": "Vietnam", "capital": "Hanoi", "continent": "Asia"},
{"name": "Philippines", "capital": "Manila", "continent": "Asia"},
{"name": "Malaysia", "capital": "Kuala Lumpur", "continent": "Asia"},
{"name": "Singapore", "capital": "Singapore", "continent": "Asia"},
{"name": "Israel", "capital": "Jerusalem", "continent": "Asia"} 
]